--Schema 1
CREATE TABLE HR.TOWN (
Id NUMBER CONSTRAINT town_id_pk PRIMARY KEY,
Name VARCHAR2(24) NOT NULL
);

CREATE TABLE HR.CUSTOMER (
Id NUMBER CONSTRAINT customer_id_pk PRIMARY KEY,
Name VARCHAR2(40) NOT NULL,
Surname VARCHAR2(40) NOT NULL,
Dob DATE NOT NULL,
Email VARCHAR2(40),
Gender VARCHAR2(10) NOT NULL,
Residence_number VARCHAR2(20) NOT NULL,
Street VARCHAR2(40) NOT NULL,
town_id NUMBER NOT NULL,

CONSTRAINT customer_town_fk FOREIGN KEY(town_id)
  REFERENCES HR.TOWN(Id)
);

CREATE TABLE HR.ORDERt (
Id NUMBER CONSTRAINT ordert_id_pk PRIMARY KEY,
Orderdate DATE NOT NULL,
customer_id NUMBER NOT NULL,

CONSTRAINT ordert_customer_fk FOREIGN KEY(customer_id)
  REFERENCES HR.CUSTOMER(Id)
);

CREATE TABLE HR.CATEGORY (
Id NUMBER CONSTRAINT category_id_pk PRIMARY KEY,
Name VARCHAR2(40) NOT NULL
);

CREATE TABLE HR.BRAND (
Id NUMBER CONSTRAINT brand_id_pk PRIMARY KEY,
Name VARCHAR2(40) NOT NULL
);

CREATE TABLE HR.PRODUCT (
Id NUMBER CONSTRAINT product_id_pk PRIMARY KEY,
Name VARCHAR2(40) NOT NULL,
Weight VARCHAR2(10) NOT NULL,
Expiry_date DATE,
Price NUMBER(6,2) NOT NULL,
category_id NUMBER NOT NULL,
brand_id NUMBER NOT NULL,

CONSTRAINT product_category_fk FOREIGN KEY(category_id)
  REFERENCES HR.CATEGORY(Id),
CONSTRAINT product_brand_fk FOREIGN KEY(brand_id)
  REFERENCES HR.BRAND(Id)
);

CREATE TABLE HR.ORDERITEM (
ordert_id NUMBER NOT NULL,
product_id NUMBER NOT NULL,
Quantity VARCHAR2(30) NOT NULL,

CONSTRAINT order_item_ordert_id_fk FOREIGN KEY(ordert_id)
    REFERENCES HR.ORDERt(Id),
CONSTRAINT order_item_product_id_fk FOREIGN KEY(product_id)
    REFERENCES HR.PRODUCT(Id),

CONSTRAINT order_iop_id_pk PRIMARY KEY(ordert_id, product_id)
);

--Schema 2
CREATE TABLE HR.TIME_DIM (
Time_Id NUMBER CONSTRAINT time_dim_id_pk PRIMARY KEY,
Day VARCHAR2(10) NOT NULL,
Month VARCHAR2(10) NOT NULL,
Year VARCHAR2(10) NOT NULL
);

CREATE TABLE HR.PRODUCT_DIM (
Product_Id NUMBER CONSTRAINT product_time_id_pk PRIMARY KEY,
Pid NUMBER NOT NULL,
Brand VARCHAR2(20) NOT NULL,
Category VARCHAR2(20) NOT NULL
);

CREATE TABLE HR.CUSTOMER_DIM (
Customer_Id NUMBER CONSTRAINT customer_dim_id_pk PRIMARY KEY,
Cid VARCHAR2(10) NOT NULL,
Age NUMBER(10) NOT NULL,
Town VARCHAR2(20) NOT NULL
);

CREATE TABLE HR.SALES_FACT (
product_id NUMBER NOT NULL,
customer_id NUMBER NOT NULL,
time_id NUMBER NOT NULL,
Quantity VARCHAR2(30) NOT NULL,
Price NUMBER(6,2) NOT NULL,


CONSTRAINT product_fk FOREIGN KEY (product_id)
  REFERENCES HR.PRODUCT_DIM (Product_Id),
CONSTRAINT customer_fk FOREIGN KEY (customer_id)
  REFERENCES HR.CUSTOMER_DIM (Customer_Id),
CONSTRAINT time_fk FOREIGN KEY (time_id)
  REFERENCES HR.TIME_DIM (Time_Id),

CONSTRAINT pk PRIMARY KEY (product_id, customer_id, time_id)
);

--Schema 3
CREATE TABLE HR.CATEGORY_DIM_SF (
Category_Id NUMBER CONSTRAINT category_dim_pk PRIMARY KEY,
Cid NUMBER NOT NULL,
name VARCHAR(40) NOT NULL
);

CREATE TABLE HR.BRAND_DIM_SF (
Brand_Id NUMBER CONSTRAINT brand_dim_sf_id_pk PRIMARY KEY,
Bid NUMBER NOT NULL,
Name VARCHAR(40) NOT NULL
);

CREATE TABLE HR.PRODUCT_DIM_SF (
Product_Id NUMBER CONSTRAINT product_dim_sf_id_pk PRIMARY KEY,
Pid NUMBER NOT NULL,
category_id NUMBER NOT NULL,
brand_id NUMBER NOT NULL,

CONSTRAINT category_dim_sf_id_fk FOREIGN KEY(category_id)
  REFERENCES HR.CATEGORY_DIM_SF(Category_Id),
CONSTRAINT brand_dim_sf_id_fk FOREIGN KEY(brand_id)
  REFERENCES HR.BRAND_DIM_SF(Brand_Id)
);

CREATE TABLE HR.TIME_DIM_SF (
Time_Id NUMBER CONSTRAINT time_dim_sf_id_pk PRIMARY KEY,
Day VARCHAR2(10) NOT NULL,
Month VARCHAR2(10) NOT NULL,
Year VARCHAR2(10) NOT NULL
);

CREATE TABLE HR.TOWN_DIM_SF (
Town_Id NUMBER CONSTRAINT town_dim_sf_id_pk PRIMARY KEY,
Tid NUMBER NOT NULL,
Name VARCHAR2(40)
);

CREATE TABLE HR.CUSTOMER_DIM_SF (
Customer_Id NUMBER CONSTRAINT customer_dim_sf_pk PRIMARY KEY,
Cid NUMBER NOT NULL,
Age NUMBER(3),
town_id NUMBER NOT NULL,

CONSTRAINT town_dim_sf_id_fk FOREIGN KEY(town_id)
  REFERENCES HR.TOWN_DIM_SF(Town_Id)
);

CREATE TABLE HR.SALES_FACT_SF (
product_id NUMBER NOT NULL,
customer_id NUMBER NOT NULL,
time_id NUMBER NOT NULL,
Quantity NUMBER(10) NOT NULL,
Price NUMBER(6,2) NOT NULL,

CONSTRAINT time_dim_sf_fk FOREIGN KEY(time_id)
  REFERENCES HR.TIME_DIM_SF(Time_Id),
CONSTRAINT product_dim_sf_id_fk FOREIGN KEY(product_id)
  REFERENCES HR.PRODUCT_DIM_SF(Product_Id),
CONSTRAINT customer_dim_sf_id FOREIGN KEY(customer_id)
  REFERENCES HR.CUSTOMER_DIM_SF(Customer_Id),

CONSTRAINT sales_fact_sf_pk PRIMARY KEY(time_id, product_id, customer_id)
);
