DROP TABLE HR.TOWN CASCADE CONSTRAINTS;
DROP TABLE HR.CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE HR.ORDERt CASCADE CONSTRAINTS;
DROP TABLE HR.CATEGORY CASCADE CONSTRAINTS;
DROP TABLE HR.BRAND CASCADE CONSTRAINTS;
DROP TABLE HR.PRODUCT CASCADE CONSTRAINTS;
DROP TABLE HR.ORDERITEM CASCADE CONSTRAINTS;

-- 2) ERD for an OLAP system (Star Schema)
DROP TABLE HR.TIME_DIM CASCADE CONSTRAINTS;
DROP TABLE HR.CUSTOMER_DIM CASCADE CONSTRAINTS;
DROP TABLE HR.PRODUCT_DIM CASCADE CONSTRAINTS;
DROP TABLE HR.SALES_FACT CASCADE CONSTRAINTS;

-- 3) ERD for an OLAP system (Snowflake Schema)
DROP TABLE HR.BRAND_DIM_SF CASCADE CONSTRAINTS;
DROP TABLE HR.CATEGORY_DIM_SF CASCADE CONSTRAINTS;
DROP TABLE HR.TIME_DIM_SF CASCADE CONSTRAINTS;
DROP TABLE HR.TOWN_DIM_SF CASCADE CONSTRAINTS;
DROP TABLE HR.CUSTOMER_DIM_SF CASCADE CONSTRAINTS;
DROP TABLE HR.PRODUCT_DIM_SF CASCADE CONSTRAINTS;
DROP TABLE HR.SALES_FACT_SF CASCADE CONSTRAINTS;
